# Generated by Django 4.1.2 on 2022-11-01 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_order_client_email_alter_order_client_fname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                help_text="Payment Method",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payment_methods",
                to="store.paymentchannel",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                help_text="Choose product to buy",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="store.product",
            ),
        ),
    ]
