# Generated by Django 3.1.13 on 2021-12-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=512)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('school', models.CharField(blank=True, max_length=256)),
                ('age', models.CharField(blank=True, default='9-12', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
