# Generated by Django 3.1.13 on 2021-12-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='payment',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
