# Generated by Django 4.1.2 on 2022-10-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_kid_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kid",
            name="phone_number",
            field=models.CharField(max_length=16),
        ),
    ]
