# Generated by Django 4.1.2 on 2022-10-23 05:25

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_from_address_homepage_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="form_title",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
