# Generated by Django 4.1.2 on 2022-10-25 15:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_body_divs_homepage_form_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body_divs",
            field=wagtail.fields.StreamField(
                [
                    (
                        "landing_banner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.RichTextBlock(
                                        default="Online Coding for kids Not Just A Course Its A Learning Journey",
                                        form_classname="h2",
                                        help_text="Dispalay as a heading bold text",
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        default="Start your child's Online Coding Journey for only 999 EGP New Year's Offer!",
                                        help_text="Dispalay as a description text",
                                    ),
                                ),
                                (
                                    "hero_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="A hero image"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
