# Generated by Django 4.1.2 on 2022-10-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_form_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="submit_button",
            field=models.CharField(default="Submit", max_length=255),
        ),
    ]
