# Generated by Django 4.1.2 on 2022-10-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_homepage_submit_button"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="form_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
