# Generated by Django 4.1.2 on 2022-10-25 14:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_homepage_form_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "landing_banner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Dispalay as a heading bold text"
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Dispalay as a description text"
                                    ),
                                ),
                                (
                                    "hero_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="A hero image"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
